version: '3.7'

services:
  nginx:
    build: nginx
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - ${WEB_INTERFACE_PORT}:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates:rw,cached
      - ./backend/static/:/app/static/
      - ./backend/media/:/app/media/
    depends_on:
      - db
      - backend
    restart: always
  backend:
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - DB_ENGINE=${DJANGO_DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DJANGO_DB_HOST}
      - DB_PORT=${DJANGO_DB_PORT}
      - ALLOWED_HOSTS=${DOMAIN}
      - COLLECT_STATIC=${DJANGO_COLLECT_STATIC}
      - DEBUG=${DEBUG}
    build: backend
    volumes:
      - ./backend/:/app/
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always

volumes:
  postgres_data:
