#!/bin/bash

./create_requirements

source .env

echo "$HEROKU_TEST_APP_NAME" | heroku pg:reset --app $HEROKU_TEST_APP_NAME

git push heroku_test master

heroku ps:restart --app $HEROKU_TEST_APP_NAME
