#!/bin/bash

./create_requirements

source .env

heroku buildpacks:clear --app $HEROKU_TEST_APP_NAME
heroku buildpacks:add https://github.com/SectorLabs/heroku-buildpack-subdir.git --app $HEROKU_TEST_APP_NAME
heroku config:set \
  COLLECT_STATIC=$DJANGO_COLLECT_STATIC \
 --app $HEROKU_TEST_APP_NAME

heroku git:remote -a $HEROKU_TEST_APP_NAME --remote heroku_test